Adding check_ints.c and TEST returns non-0 on failure

diff --git a/trunk/t/TEST b/trunk/t/TEST
--- a/trunk/t/TEST
+++ b/trunk/t/TEST
@@ -14,16 +14,18 @@ export STAMPDIR=.
  
 cd $tdir
 
+failed=0
+
 for file in `ls *.t | sort -n`
 do
     test=${file%\.t}
     source $file
-    if [ $? = 0 ]
-    then
-	echo "test $test - ok";
-	let passed++
+    if [ $? = 0 ]; then
+	    echo "test $test - ok";
+	    let passed++
     else
-	echo "test $test - failed.";
+	    echo "test $test - failed.";
+        failed=1
     fi
     let total++
 done
@@ -33,3 +35,5 @@ done
 echo "passed $passed/$total."
 
 cd -
+
+exit $failed;
